# Generated by Django 3.2.7 on 2021-10-03 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True)),
                ('prize', models.CharField(max_length=64, null=True)),
                ('year', models.PositiveSmallIntegerField(default=2000)),
            ],
        ),
    ]
