# Generated by Django 3.2.7 on 2021-10-03 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='imbd_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='film',
            name='poster',
            field=models.ImageField(null=True, upload_to='posters'),
        ),
        migrations.AddField(
            model_name='film',
            name='premiere',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='review',
            field=models.TextField(default=''),
        ),
    ]
