# Generated by Django 3.2.7 on 2021-10-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0003_alter_film_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.ImageField(blank=True, height_field=30, null=True, upload_to='posters', width_field=10),
        ),
    ]
