# Generated by Django 3.2.7 on 2021-11-08 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0005_alter_film_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveSmallIntegerField(default=0)),
                ('film_genre', models.PositiveSmallIntegerField(choices=[(5, 'Drama'), (11, 'Western'), (8, 'Horror film'), (6, 'Fantasy film'), (10, 'Thriller film'), (4, 'Comedy film'), (1, 'Action film'), (3, 'Animated film'), (9, 'Science fiction film'), (0, 'Other'), (2, 'Adventure film'), (7, 'Historical film')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='extra',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filmapp.extrainfo'),
        ),
    ]
