# Generated by Django 3.2.7 on 2021-11-08 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0006_auto_20211108_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='film_genre',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Comedy film'), (3, 'Animated film'), (7, 'Historical film'), (2, 'Adventure film'), (11, 'Western'), (10, 'Thriller film'), (1, 'Action film'), (9, 'Science fiction film'), (6, 'Fantasy film'), (0, 'Other'), (8, 'Horror film'), (5, 'Drama')], default=0),
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('personal_review', models.TextField(default='')),
                ('film_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmapp.film')),
            ],
        ),
    ]
