# Generated by Django 3.2.7 on 2021-11-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0007_auto_20211108_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='film_genre',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Adventure film'), (0, 'Other'), (11, 'Western'), (9, 'Science fiction film'), (4, 'Comedy film'), (10, 'Thriller film'), (1, 'Action film'), (7, 'Historical film'), (3, 'Animated film'), (8, 'Horror film'), (5, 'Drama'), (6, 'Fantasy film')], default=0),
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('surname', models.CharField(max_length=32, unique=True)),
                ('film_perforn', models.ManyToManyField(to='filmapp.Film')),
            ],
        ),
    ]
