# Generated by Django 3.2.7 on 2021-11-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0008_auto_20211109_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='film_genre',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Thriller film'), (5, 'Drama'), (1, 'Action film'), (2, 'Adventure film'), (4, 'Comedy film'), (7, 'Historical film'), (9, 'Science fiction film'), (3, 'Animated film'), (8, 'Horror film'), (6, 'Fantasy film'), (11, 'Western'), (0, 'Other')], default=0),
        ),
    ]
